name: Python Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      app:
        image: tiangolo/uvicorn-gunicorn-fastapi:python3.11
        ports:
          - 8000:80
        env:
          MODULE_NAME: src.main
          PYTHONPATH: /app
        options: >-
          --health-cmd "curl --fail http://localhost:80/users || exit 1"
          --health-interval 5s
          --health-timeout 5s
          --health-retries 10
        volumes:
          - ./:/app

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest pytest-html requests

      - name: Wait for FastAPI app
        run: |
          for i in {1..20}; do
            if curl -s http://localhost:8000/users; then
              echo "App is up!"
              break
            fi
            echo "Waiting for app..."
            sleep 2
          done

      - name: Run tests
        env:
          BASE_URL: http://localhost:8000
        run: |
          pytest --html=report.html